### ISSUE TITLE
multiple input directories

### ISSUE THREAD

**Issue by clux** [clux/symlink#4]
We should be able to symlink across multiple root directories.

This is useful once the set of repositories becomes so large that categorization feels necessary.

**Comment by joshuajabbour** [comment]
:+1: 

This would be very useful for me. I've got this structure:

- root
  - package1
  - package2
  - package3
  - examples-repo
    - example1
    - example2

If I run `symlink .` from the root, all the packages get connected properly. But I'd like to also link the packages into each of the examples. If `symlink . ./examples-repo` worked, this would be truly magic!

**Comment by clux** [comment]
Yeah. It's been a while, and this module is still very useful to me - deserves an update. Hopefully, I'll have some time to look at it before easter.

**Comment by joshuajabbour** [comment]
Very excellent! I was going to attempt adding this over the weekend, because I really wanted this. Thanks!

**Comment by clux** [comment]
Implemented in symlink@1.0.0

Turned out to be easier than I thought.

**Comment by clux** [comment]
Hehe, no worries. Glad you like the module :]
