### ISSUE TITLE
Dev dependencies are added to dependencies

### ISSUE THREAD

**Issue by raypatterson** [clux/symlink#5]
HI,

Thanks for this tool, it is the best one I've found for my needs. 

I am seeing one issue where `devDependencies` are being copied to the `dependencies` list.

Just wondering if I'm doing something wrong, or if I should clean up the copies so my `package.json` isn't changed.

**Comment by clux** [comment]
Hey, glad you like it :)

I am not sure I understand your issue though. Are you saying `symlink` modifies your package.json? It should only read it. The only way it could modify it if `npm install` is aliased to always `--save` or something. Do you have an example for reproducing this?

**Comment by raypatterson** [comment]
Oh duh, that's it! I'd added an `.npmrc` file with `save=true` ... Didn't expect this to cause `devDependencies` to be saved as `dependencies` on install but it looks like that's what's happening.

**Comment by clux** [comment]
Ah good. Yeah, the save flags look a little dumb in that aspect. `npm install` itself will read and obey dependency version ranges, but the `--save` flag seems to be just a post-install thing that has no checks.
Oh well. Thanks for letting me now.

**Comment by raypatterson** [comment]
Thanks for helping me understand the problem.
